### ISSUE TITLE
thumbor returns 500 when trying to convert images with size < 64 to jpeg2000

### ISSUE THREAD

**Issue by bagipriyank** [thumbor/thumbor-plugins#26]
```http://localhost:8000/unsafe/133x63/filters:format(jp2)/some/image.jpg``` resulted in 
```
2018-06-06 00:58:38 thumbor:ERROR [ThreadPool] encoder error -2 when writing image file
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/thumbor/context.py", line 268, in _execute_in_foreground
    returned = operation()
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 339, in _load_results
    results = self.optimize(context, image_extension, results)
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 465, in optimize
    new_results = optimizer(context).run_optimizer(image_extension, results)
  File "/usr/local/lib/python2.7/site-packages/thumbor/optimizers/__init__.py", line 34, in run_optimizer
    self.optimize(buffer, ifile.name, ofile.name)
  File "/usr/local/lib/python2.7/site-packages/thumbor_plugins/optimizers/jp2.py", line 33, in optimize
    return Image.open(input_file).save(output_file, 'JPEG2000', quality_mode='dB', quality_layers=[self.jp2_quality])
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 1698, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python2.7/site-packages/PIL/Jpeg2KImagePlugin.py", line 264, in _save
    ImageFile._save(im, fp, [('jpeg2k', (0, 0)+im.size, 0, kind)])
  File "/usr/local/lib/python2.7/site-packages/PIL/ImageFile.py", line 500, in _save
    raise IOError("encoder error %d when writing image file" % s)
IOError: encoder error -2 when writing image file
2018-06-06 00:58:38 thumbor:ERROR [BaseHander.finish_request] encoder error -2 when writing image file
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 386, in inner
    future_result = future.result()
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
IOError: encoder error -2 when writing image file
2018-06-06 00:58:38 thumbor:WARNING Error while trying to fetch the image: encoder error -2 when writing image file
```

i am running thumbor via a docker as follows:
```
docker run -e AWS_ACCESS_KEY_ID='XXXX' -e AWS_SECRET_ACCESS_KEY='YYYY' -e TC_AWS_LOADER_BUCKET='mybucket' -e LOADER='tc_aws.loaders.presigning_loader' -e TC_AWS_REGION='us-east-1' -e TC_AWS_ENABLE_HTTP_LOADER='True' -e RESULT_STORAGE_STORES_UNSAFE='False' -e STORES_CRYPTO_KEY_FOR_EACH_IMAGE='False' -e TC_AWS_STORE_METADATA='False' -e OPTIMIZERS="['thumbor_plugins.optimizers.jp2']" -e ENGINE='thumbor.engines.pil' -e MAX_AGE='604800' -e QUALITY='100' -p 8000:8000 docker-thumbor
```

On the other hand: ```http://localhost:8000/unsafe/133x64/filters:format(jp2)/some/image.jpg``` has no issues.

**Comment by bagipriyank** [comment]
opened https://github.com/python-pillow/Pillow/issues/3161 with Pillow. Closing this one.
