### ISSUE TITLE
No module named pngcrush

### ISSUE THREAD

**Issue by onerandomgig** [thumbor/thumbor-plugins#9]
Hello,
I have installed both the gifsicle and pngcrush packages. But after installing the optimizer plugins, when i run thumor, i get a No module found error.

This is the error i m getting.

Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 9, in <module>
    load_entry_point('thumbor==5.0.6', 'console_scripts', 'thumbor')()
  File "/usr/local/lib/python2.7/dist-packages/thumbor/server.py", line 58, in main
    importer.import_modules()
  File "/usr/local/lib/python2.7/dist-packages/thumbor/importer.py", line 50, in import_modules
    self.import_item('OPTIMIZERS', 'Optimizer', is_multiple=True)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/importer.py", line 74, in import_item
    module = self.import_class('%s.%s' % (module_name, class_name))
  File "/usr/local/lib/python2.7/dist-packages/thumbor/importer.py", line 33, in import_class
    module = get_module and __import__(name) or __import__(module_name)
ImportError: No module named pngcrush

**Comment by guilhermef** [comment]
The pngcrush module should be imported as 'thumbor_plugins.optimizers.pngcrush'
